plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "tailwindcss-radix@*":
    dependencies:
      tailwindcss: "*"

  "chalk@5.0.1":
    dependencies:
      "#supports-color": npm:supports-color@^9.2.2
      "#ansi-styles": npm:ansi-styles@^6.1.0

pnpIgnorePatterns: "./plugins/*"

nodeLinker: "pnp"
pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
