(function(s,a){typeof exports=="object"&&typeof module!="undefined"?a(exports,require("@fuse-labs/core-client"),require("@fuse-labs/core-ui"),require("react")):typeof define=="function"&&define.amd?define(["exports","@fuse-labs/core-client","@fuse-labs/core-ui","react"],a):(s=typeof globalThis!="undefined"?globalThis:s||self,a(s["@fuse-labs/marlin-settings"]={},s.coreClient,s.coreUi,s.React))})(this,function(s,a,O,p){"use strict";function j(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}var _=j(p),c={exports:{}},f={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var g=Object.getOwnPropertySymbols,S=Object.prototype.hasOwnProperty,h=Object.prototype.propertyIsEnumerable;function w(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function P(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var r={},t=0;t<10;t++)r["_"+String.fromCharCode(t)]=t;var n=Object.getOwnPropertyNames(r).map(function(i){return r[i]});if(n.join("")!=="0123456789")return!1;var o={};return"abcdefghijklmnopqrst".split("").forEach(function(i){o[i]=i}),Object.keys(Object.assign({},o)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}P();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var x=_.default,b=60103;if(f.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var m=Symbol.for;b=m("react.element"),f.Fragment=m("react.fragment")}var E=x.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,M=Object.prototype.hasOwnProperty,T={key:!0,ref:!0,__self:!0,__source:!0};function y(e,r,t){var n,o={},i=null,u=null;t!==void 0&&(i=""+t),r.key!==void 0&&(i=""+r.key),r.ref!==void 0&&(u=r.ref);for(n in r)M.call(r,n)&&!T.hasOwnProperty(n)&&(o[n]=r[n]);if(e&&e.defaultProps)for(n in r=e.defaultProps,r)o[n]===void 0&&(o[n]=r[n]);return{$$typeof:b,type:e,key:i,ref:u,props:o,_owner:E.current}}f.jsx=y,f.jsxs=y,c.exports=f;const d=c.exports.jsx,C=c.exports.Fragment;function v(){const{device:e}=a.useDeviceContext();return p.useEffect(r=>{e.sockets.fuseLabs.marlinSettings.emit("settings:read",e.id,t=>{console.log("NEW SYSTEM - Sent request for Marlin settings",t)})},[e.id,e.sockets.fuseLabs.marlinSettings]),d(O.Widget,{title:"Marlin settings",children:"TODO - Show Marlin settings"})}function R(){return d(C,{children:d(v,{})})}class q extends a.ClientPlugin{deviceComponents(r){return{page:{plugin:R}}}}s.MarlinSettingsWidget=v,s.default=q,Object.defineProperties(s,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
