const enum GRBLSettingId {
  STEP_PULSE = 0,
  STEP_DELAY = 1,
  STEP_PORT_INVERT = 2,
  DIRECTION_PORT_INVERT = 3,
  STEP_ENABLE_INVERT = 4,
  LIMIT_PINS_INVERT = 5,
  PROBE_PIN_INVERT = 6,

  STATUS_REPORT = 10,
  JUNCTION_DEVIATION = 11,
  ARC_TOLERANCE = 12,
  REPORT_INCHES = 13,

  SOFT_LIMITS = 20,
  HARD_LIMITS = 21,
  HOMING_CYCLE = 22,
  HOMING_DIR_INVERT = 23,
  HOMING_FEED = 24,
  HOMING_SEEK = 25,
  HOMING_DEBOUNCE = 26,
  HOMING_PULL_OFF = 27,

  MAX_SPINDLE_SPEED = 30,
  MIN_SPINDLE_SPEED = 31,
  LASER_MODE = 32,

  X_STEPS_ON_MM = 100,
  Y_STEPS_ON_MM = 101,
  Z_STEPS_ON_MM = 102,

  X_MAX_RATE = 110,
  Y_MAX_RATE = 111,
  Z_MAX_RATE = 112,
  
  X_ACCELERATION = 120,
  Y_ACCELERATION = 121,
  Z_ACCELERATION = 122,

  X_MAX_TRAVEL = 130,
  Y_MAX_TRAVEL = 131,
  Z_MAX_TRAVEL = 132,
}

export default GRBLSettingId