(function(s,a){typeof exports=="object"&&typeof module!="undefined"?a(exports,require("@fuse-labs/core-client"),require("@fuse-labs/core-ui"),require("react")):typeof define=="function"&&define.amd?define(["exports","@fuse-labs/core-client","@fuse-labs/core-ui","react"],a):(s=typeof globalThis!="undefined"?globalThis:s||self,a(s["@fuse-labs/marlin-settings"]={},s.coreClient,s.coreUi,s.React))})(this,function(s,a,y,l){"use strict";function O(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}var v=O(l),p={exports:{}},u={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var d=Object.getOwnPropertySymbols,j=Object.prototype.hasOwnProperty,_=Object.prototype.propertyIsEnumerable;function S(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function h(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var t={},r=0;r<10;r++)t["_"+String.fromCharCode(r)]=r;var n=Object.getOwnPropertyNames(t).map(function(i){return t[i]});if(n.join("")!=="0123456789")return!1;var o={};return"abcdefghijklmnopqrst".split("").forEach(function(i){o[i]=i}),Object.keys(Object.assign({},o)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}h();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var w=v.default,b=60103;if(u.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var g=Symbol.for;b=g("react.element"),u.Fragment=g("react.fragment")}var E=w.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,x=Object.prototype.hasOwnProperty,P={key:!0,ref:!0,__self:!0,__source:!0};function m(e,t,r){var n,o={},i=null,f=null;r!==void 0&&(i=""+r),t.key!==void 0&&(i=""+t.key),t.ref!==void 0&&(f=t.ref);for(n in t)x.call(t,n)&&!P.hasOwnProperty(n)&&(o[n]=t[n]);if(e&&e.defaultProps)for(n in t=e.defaultProps,t)o[n]===void 0&&(o[n]=t[n]);return{$$typeof:b,type:e,key:i,ref:f,props:o,_owner:E.current}}u.jsx=m,u.jsxs=m,p.exports=u;const T=p.exports.jsx;function M(){const{device:e}=a.useDeviceContext();return l.useEffect(t=>{e.sockets.fuseLabs.marlinSettings.emit("settings:read",e.id,r=>{console.log("NEW SYSTEM - Sent request for Marlin settings",r)})},[e.id,e.sockets.fuseLabs.marlinSettings]),T(y.Widget,{title:"Marlin settings",children:"TODO - Show Marlin settings"})}s.MarlinSettingsWidget=M,Object.defineProperties(s,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
