(function(a,u){typeof exports=="object"&&typeof module!="undefined"?u(exports,require("@fuse-labs/core-ui"),require("react"),require("@radix-ui/react-aspect-ratio")):typeof define=="function"&&define.amd?define(["exports","@fuse-labs/core-ui","react","@radix-ui/react-aspect-ratio"],u):(a=typeof globalThis!="undefined"?globalThis:a||self,u(a["@fuse-labs/marlin-gcode-viewer"]={},a.coreUi,a.React,a.AspectRatio))})(this,function(a,u,g,j){"use strict";function v(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}function O(e){if(e&&e.__esModule)return e;var t=Object.create(null,{[Symbol.toStringTag]:{value:"Module"}});return e&&Object.keys(e).forEach(function(r){if(r!=="default"){var n=Object.getOwnPropertyDescriptor(e,r);Object.defineProperty(t,r,n.get?n:{enumerable:!0,get:function(){return e[r]}})}}),t.default=e,Object.freeze(t)}var _=v(g),w=O(j),d={exports:{}},f={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var p=Object.getOwnPropertySymbols,h=Object.prototype.hasOwnProperty,S=Object.prototype.propertyIsEnumerable;function x(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function P(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var t={},r=0;r<10;r++)t["_"+String.fromCharCode(r)]=r;var n=Object.getOwnPropertyNames(t).map(function(i){return t[i]});if(n.join("")!=="0123456789")return!1;var o={};return"abcdefghijklmnopqrst".split("").forEach(function(i){o[i]=i}),Object.keys(Object.assign({},o)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}P();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var R=_.default,b=60103;if(f.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var m=Symbol.for;b=m("react.element"),f.Fragment=m("react.fragment")}var E=R.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,C=Object.prototype.hasOwnProperty,N={key:!0,ref:!0,__self:!0,__source:!0};function y(e,t,r){var n,o={},i=null,s=null;r!==void 0&&(i=""+r),t.key!==void 0&&(i=""+t.key),t.ref!==void 0&&(s=t.ref);for(n in t)C.call(t,n)&&!N.hasOwnProperty(n)&&(o[n]=t[n]);if(e&&e.defaultProps)for(n in t=e.defaultProps,t)o[n]===void 0&&(o[n]=t[n]);return{$$typeof:b,type:e,key:i,ref:s,props:o,_owner:E.current}}f.jsx=y,f.jsxs=y,d.exports=f;const c=d.exports.jsx,M=d.exports.jsxs;function T(){return c(u.SettingsWidget,{children:M(u.Group,{className:"justify-between",children:[c(u.Label,{htmlFor:"mode",children:"Display mode"}),c(u.SelectRaw,{id:"mode",options:[{value:"2d",label:"2D"},{value:"3d",label:"3D"}]})]})})}function q(){return c(u.Widget,{title:"GCode Viewer",version:"0.1",children:c(w.Root,{ratio:4/3,className:"rounded-sm bg-gray-500"})})}a.MarlinGCodeViewerSettingsWidget=T,a.MarlinGCodeViewerWidget=q,Object.defineProperties(a,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
