(function(i,f){typeof exports=="object"&&typeof module!="undefined"?f(exports,require("@radix-ui/react-icons"),require("@fuse-labs/core-ui"),require("react")):typeof define=="function"&&define.amd?define(["exports","@radix-ui/react-icons","@fuse-labs/core-ui","react"],f):(i=typeof globalThis!="undefined"?globalThis:i||self,f(i["@fuse-labs/marlin-extra"]={},i.reactIcons,i.coreUi,i.React))})(this,function(i,f,p,O){"use strict";function _(e){return e&&typeof e=="object"&&"default"in e?e:{default:e}}var g=_(O),d={exports:{}},u={};/*
object-assign
(c) Sindre Sorhus
@license MIT
*/var b=Object.getOwnPropertySymbols,h=Object.prototype.hasOwnProperty,x=Object.prototype.propertyIsEnumerable;function w(e){if(e==null)throw new TypeError("Object.assign cannot be called with null or undefined");return Object(e)}function S(){try{if(!Object.assign)return!1;var e=new String("abc");if(e[5]="de",Object.getOwnPropertyNames(e)[0]==="5")return!1;for(var r={},t=0;t<10;t++)r["_"+String.fromCharCode(t)]=t;var n=Object.getOwnPropertyNames(r).map(function(s){return r[s]});if(n.join("")!=="0123456789")return!1;var o={};return"abcdefghijklmnopqrst".split("").forEach(function(s){o[s]=s}),Object.keys(Object.assign({},o)).join("")==="abcdefghijklmnopqrst"}catch{return!1}}S();/** @license React v17.0.2
 * react-jsx-runtime.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var E=g.default,y=60103;if(u.Fragment=60107,typeof Symbol=="function"&&Symbol.for){var j=Symbol.for;y=j("react.element"),u.Fragment=j("react.fragment")}var P=E.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner,R=Object.prototype.hasOwnProperty,N={key:!0,ref:!0,__self:!0,__source:!0};function v(e,r,t){var n,o={},s=null,a=null;t!==void 0&&(s=""+t),r.key!==void 0&&(s=""+r.key),r.ref!==void 0&&(a=r.ref);for(n in r)R.call(r,n)&&!N.hasOwnProperty(n)&&(o[n]=r[n]);if(e&&e.defaultProps)for(n in r=e.defaultProps,r)o[n]===void 0&&(o[n]=r[n]);return{$$typeof:y,type:e,key:s,ref:a,props:o,_owner:P.current}}u.jsx=v,u.jsxs=v,d.exports=u;const l=d.exports.jsx,m=d.exports.jsxs;function q(){return m(p.Widget,{title:"Extra",version:"0.1",children:[m(p.Button,{children:[l("span",{className:"mr-1",children:"Stop motors"}),l(f.Cross2Icon,{})]}),m("div",{className:"flex flex-row space-x-2",children:[l("span",{children:"Fan status"}),l(p.SwitchRaw,{})]})]})}i.MarlinMiscWidget=q,Object.defineProperties(i,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});
